---
required_packages: 
  - httpd
  - libselinux-python3

service_state: started
service_enabled: true

httpd_conf:
  - Include conf/ebilling.conf
  - Include conf/epayments.conf
  - Include conf/github.conf

proxy_conf:
  - ebilling.conf
  - epayments.conf
  - github.conf