---  
- hosts: localhost
  become: true
  gather_facts: yes
  collections: 
  - ch_collections.base
  roles:
    - name: ch_collections.base.cloudwatch_agent_config
      when: cw_log_files is defined